hubot-self-uptime
=================

Because hubot-uptime was already taken, and doesn't provide hubot's uptime
